# Generated by Django 5.0 on 2024-01-12 12:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_cart_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='card_pan',
            field=models.CharField(default=0, max_length=500),
        ),
        migrations.AddField(
            model_name='payment',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='payment',
            name='refid',
            field=models.CharField(default=0, max_length=500),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='payment',
            name='token',
            field=models.CharField(default=0, max_length=500),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(default=0, max_length=500),
        ),
        migrations.CreateModel(
            name='PaymentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=500)),
                ('mobile_number', models.CharField(max_length=11)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email address')),
                ('discount', models.CharField(blank=True, default=0, max_length=100, null=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.payment')),
            ],
        ),
    ]
