# Generated by Django 5.0 on 2024-01-12 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_paymentinfo_address_alter_paymentinfo_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinfo',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.payment'),
        ),
    ]
