# Generated by Django 5.0 on 2023-12-28 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='cart_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.cart'),
        ),
    ]
