# Generated by Django 5.0 on 2024-01-14 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_paymentinfo_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentinfo',
            name='payment',
        ),
        migrations.AddField(
            model_name='paymentinfo',
            name='cart_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='shop.cart'),
            preserve_default=False,
        ),
    ]
