# Generated by Django 5.0 on 2024-01-14 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_remove_paymentinfo_payment_paymentinfo_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinfo',
            name='cart_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.cart'),
        ),
    ]
