# Generated by Django 5.0 on 2023-12-29 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_cart_user_id'),
        ('user', '0002_user_remove_userinfo_user_id_delete_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Userinfo',
        ),
    ]
